from collections import OrderedDict
import tensorflow as tf

'''
Feature spec for reading/writing tf records
'''
features_dict_ = OrderedDict([('blue_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_0',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_1',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_2',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_3',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_4',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_5',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_6',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_7',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_8',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_9',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_10',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_11',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('blue_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('green_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('red_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('nir_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir1_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('swir2_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('tir_12',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('lat',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('lon',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('elev',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None)),
                              ('irr',
                               tf.io.FixedLenFeature(shape=[256, 256], dtype=tf.float32, default_value=None))])


def features_dict():
    return features_dict_


def bands():
    bands = list(features_dict_.keys())
    return bands


def features():
    features = list(features_dict_.keys())[:-1]
    return features


if __name__ == '__main__':
    pass