# ===============================================================================
# Copyright 2018 dgketchum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================

import os
FEATURE_NAMES = ['B2',
                 'B2_1',
                 'B2_2',
                 'B2_3',
                 'B3',
                 'B3_1',
                 'B3_2',
                 'B3_3',
                 'B4',
                 'B4_1',
                 'B4_2',
                 'B4_3',
                 'B5',
                 'B5_1',
                 'B5_2',
                 'B5_3',
                 'B6',
                 'B6_1',
                 'B6_2',
                 'B6_3',
                 'B7',
                 'B7_1',
                 'B7_2',
                 'B7_3',
                 'LAT_GCS',
                 'Lon_GCS',
                 'aspect',
                 'cdl',
                 'elevation',
                 'nd_max_cy',
                 'nd_max_m1',
                 'nd_max_m2',
                 'nlcd',
                 'pet_total_espr',
                 'pet_total_fl',
                 'pet_total_lspr',
                 'pet_total_smr',
                 'pet_total_wy',
                 'pet_total_wy_espr',
                 'pet_total_wy_espr_1',
                 'pet_total_wy_smr',
                 'prec',
                 'prec_1',
                 'prec_10',
                 'prec_11',
                 'prec_2',
                 'prec_3',
                 'prec_4',
                 'prec_5',
                 'prec_6',
                 'prec_7',
                 'prec_8',
                 'prec_9',
                 'precip_total_espr',
                 'precip_total_fl',
                 'precip_total_lspr',
                 'precip_total_smr',
                 'precip_total_wy',
                 'precip_total_wy_espr',
                 'precip_total_wy_espr_1',
                 'precip_total_wy_smr',
                 'slope',
                 'tavg',
                 'tavg_1',
                 'tavg_10',
                 'tavg_11',
                 'tavg_2',
                 'tavg_3',
                 'tavg_4',
                 'tavg_5',
                 'tavg_6',
                 'tavg_7',
                 'tavg_8',
                 'tavg_9',
                 'tmax',
                 'tmax_1',
                 'tmax_10',
                 'tmax_11',
                 'tmax_1_1',
                 'tmax_2',
                 'tmax_2_1',
                 'tmax_3',
                 'tmax_3_1',
                 'tmax_4',
                 'tmax_4_1',
                 'tmax_5',
                 'tmax_5_1',
                 'tmax_6',
                 'tmax_6_1',
                 'tmax_7',
                 'tmax_7_1',
                 'tmax_8',
                 'tmax_8_1',
                 'tmax_9',
                 'tmin',
                 'tmin_1',
                 'tmin_10',
                 'tmin_11',
                 'tmin_1_1',
                 'tmin_2',
                 'tmin_2_1',
                 'tmin_3',
                 'tmin_3_1',
                 'tmin_4',
                 'tmin_4_1',
                 'tmin_5',
                 'tmin_5_1',
                 'tmin_6',
                 'tmin_6_1',
                 'tmin_7',
                 'tmin_7_1',
                 'tmin_8',
                 'tmin_8_1',
                 'tmin_9',
                 'tmmn_p10_cy',
                 'tmmn_p50_cy',
                 'tmmn_p90_cy',
                 'tmmx_p10_cy',
                 'tmmx_p50_cy',
                 'tmmx_p90_cy',
                 'tpi_1250',
                 'tpi_150',
                 'tpi_250',
                 'wd_est_cy',
                 'wd_est_espr',
                 'wd_est_fl',
                 'wd_est_lspr',
                 'wd_est_smr',
                 'wd_est_wy',
                 'wd_est_wy_espr',
                 'wd_est_wy_espr_1',
                 'wd_est_wy_smr']

if __name__ == '__main__':
    pass
# ========================= EOF ====================================================================
